### PR TITLE
add other sites into sitemap alternate urls

### PR DESCRIPTION
**Pull request by othbert**

### CODE REVIEW

**Comment by othbert** [comment]
Hi guys, please check this out and see if my logic is sound. 
Not sure where would be best for the eligibility check method too. I kept it in the UrlGenerator routing class as it deals with similar concepts, although it's more locally focused to the controller really. But it's just a helper method and not really related there either to a controller context.

My idea was to check both the initial route (with its locale) and its alternate sites (with locales), to determine whether those paths are eligible for inclusion for whichever site the sitemap is being generated. In order to create a situation (for testing, but also for our use case) that results in urls that should not be eligible, I removed the 'es' language from calendar taxons, and also made those routes not applicable to 'aud' site.

**Comment by javihgil** [comment]
I'm not sure the aim of testRouteForSitemapEligibility method, the routes contains locales (in paths) and sites, and I think we can cover all url generation with loops.

We was thinking about creating a specific service to generate the sitemap content, so if it's necessary it could be there, we'd like to keep UrlGenerator as "cleaner" as posible.

**Comment by javihgil** [comment]
Please, run "vendor/bin/php-cs-fixer fix" to keep format and pass checks :)

**Comment by othbert** [comment]
Thanks for checking this over :)
The testRouteForSitemapEligibility was in UrlGenerator because I was using the methods there originally until I realised nothing quite exactly matched what was needed for the logic of the sitemap. Then I started to adapt the getRoutePath method, but that was also the wrong approach, so in the end it just became a small check to test the properties of the route, similar to how getRoutePath is doing it, but with a clearer result for a sitemap.

This could definitely be achieved outside of UrlGenerator and inside the main sitemap() method, but I just wanted to keep it a little cleaner if possible, seeing as I already had added complexity to the loops there.

Any way that you think it works best is fine with me, I just wanted to start the ball rolling :)
Cheers!

**Comment by othbert** [comment]
closing as superseded by #204  👍🏼 thanks!

**Pull request closed without merging**
